--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adit-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: adit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: adit-server
      labels:
        app: adit
    spec: 
      containers:
        - name: adit
          image: pitstop/auditlogservice:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production 
      restartPolicy: Always                
       
---
apiVersion: v1
kind: Service 
metadata:
  name: adit-svc
spec: 
  type: NodePort 
  selector: 
    name: adit
  ports:
    - name: ram-svc
      port: 5000
      protocol: TCP 
      targetPort: 5000
      nodePort: 30000
                          
 
         