--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adit-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: adit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: adit-server
      labels:
        app: adit
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io 
                  operator: In
                  values: 
                   - instance-id=i-0b7cb85e2da9b44dd
      containers:
        - name: adit
          image: pitstop/auditlogservice:1.0
          command:
            - "dotnet"
            - "Pitstop.AuditlogService.dll"
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production 
      restartPolicy: "Always"              
      
                          
 
         