--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custmoer-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: custmoer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: custmoer-server
      labels:
        app: custmoer
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io/instance-id
                  operator:  In
                  values: 
                   - i-0b7cb85e2da9b44dd
      containers: 
        - name: custmoer
          image: pitstop/customermanagementapi:1.0
          resources:
          ports: 
            - containerPort: 5100
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production 
      restartPolicy: Always               
--- 
apiVersion: v1
kind: Service
metadata:
  name: custmoer-svc
spec:
  type: NodePort
  selector:
    app: custmoer
  ports:
    - name: mail-https
      port: 5100
      targetPort: 5100
      nodePort: 30001
         