--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custmoer-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: custmoer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: custmoer-server
      label:
        app: custmoer
    spec: 
      - containers: 
          - env:
              name: ASPNETCORE_ENVIRONMENT
              value: Production
          - name: custmoer
            image: pitstop/customermanagementapi:1.0
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            ports: 
              - containerPort: 5100
                protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: custmoer-svc
spec:
  type: "NodePort"
  selector:
    app: custmoer
  ports:
    - name: mail https
      port: 5100
      nodePort: 3006
      targetPort: 5100
         