--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoi-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: invoi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: invoi-server
      labels:
        app: invoi
    spec: 
       containers: 
          - name: invoi
            image: pitstop/invoiceservice:1.0
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m" 
            env:
              - name: DOTNET_ENVIRONMENT
                value: Production  
       restartPolicy: Always                