--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoi-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: invoi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: invoi-server
      labels:
        app: invoi
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io 
                  operator: in 
                  values: 
                   - instance-id=i-0b7cb85e2da9b44dd 
      containers: 
        - name: invoi
          image: pitstop/invoiceservice:1.0
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production  
      restartPolicy: Always                