--- 
apiVersion: apps/v1
kind: 
metadata:
  name: log-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: log
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: log-server
      label:
        app: log
    spec: 
      containers: 
        - env:
            name: ACCEPT_EULA
            value: Y
        - name: log
          image: datalust/seq:latest
          ports: 
            - containerPort: 80
              protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: log-svc
spec:
  type: Nodeport
  selector:
    app: log
  ports:
    - name: mail https
      nodePort: 3001
      targetPort: 5341
         