--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: log
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: log-server
      label:
        app: log
    spec: 
      - containers: 
         - env:
             name: ACCEPT_EULA
             value: Y
         - name: log
           image: datalust/seq:latest
           resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
           ports: 
             - containerPort: 80
               protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: log-svc
spec:
  type: "NodePort"
  selector:
    app: log
  ports:
     - name: mail https
       port: 80
       nodePort: 3001
       targetPort: 5341
         