--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
spec: 
  minReadySeconds: 2  
  replicas: 2
  selector:
    matchLabels:
      app: log
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: log-server
      labels:
        app: log
    spec: 
      containers: 
        - name: log
          image: datalust/seq:latest
          ports: 
            - containerPort: 80
              protocol: TCP 
          env:
            - name: ACCEPT_EULA
              value: "Y" 
      restartPolicy: Always            
--- 
apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  type: NodePort
  selector:
    name: log
  ports:
     - name: mail-https
       port: 80
       nodePort: 30002
       targetPort: 5341
         