--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: mail
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: mail-server
      labels:
        app: mail
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io/instance-id
                  operator:  In 
                  values: 
                   - i-0b7cb85e2da9b44dd
      containers: 
        - name: sql
          image: maildev/maildev:1.1.0
          ports: 
            - containerPort: 25
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always              
--- 
apiVersion: v1
kind: Service
metadata:
  name: mail-svc
spec:
  type: NodePort
  selector:
    name: mail
  ports:
    - name: mailtap-https
      port: 25
      targetPort: 25
    - name: mailtap-http
      port: 80
      nodePort: 30003
      targetPort: 4000          