--- 
apiVersion: apps/v1
kind: 
metadata:
  name: mail-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: mail
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: mail-server
      label:
        app: mail
    spec: 
      containers: 
        - name: sql
          image: maildev/maildev:1.1.0
          ports: 
            - containerPort: 25
            - containerPort: 80
              protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: mail-svc
spec:
  type: Nodeport
  selector:
    app: mail
  ports:
    - name: mail https
      nodePort: 25
      targetPort: 25
    - name: mail https
      nodePort: 3000
      targetPort: 4000          