--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: notificationservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: notificationservice-server
      labels:
        app: notificationservice
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io/instance-id
                  operator:  In
                  values: 
                   - i-0b7cb85e2da9b44dd
      containers: 
        - name: notificationservice
          image: pitstop/notificationservice:1.0
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production    
      restartPolicy: Always            