--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: notificationservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: notificationservice-server
      labels:
        app: notificationservice
    spec: 
      containers: 
        - name: notificationservice
          image: pitstop/notificationservice:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production    
      restartPolicy: Always            