---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rqconfigmap
data:
  rabbitmq.conf: 
    default_user = rabbitmquser
    default_pass = DEBmbwkSrzy9D1T9cJfa


--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-rabbit
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: rabbit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: my-rabbit 
      labels:
        app: rabbit
    spec: 
      containers:
          - name: rabbit 
            env:
              - name: RABBITMQ_CONFIG_FILE
                value: /etc/pitstop/rabbitmq.conf
            image: rabbitmq:3-management-alpine
            ports: 
              - containerPort: 15672
              - containerPort: 5672
                protocol: TCP
            volumeMounts: 
              name: rabbit-volume 
              mountPath: /etc/pitstop/
              readOnly: true
      volumes: 
          - name: rqconfig 
            configMap: 
              name: rqconfigmap 
      restartPolicy: Always             
--- 
apiVersion: v1
kind: Service
metadata:
  name: rabbit-svc
spec:
  type: NodePort
  selector:
    app: rabbit
  ports:
    - name: rabbit-http
      port: 15672
      targetPort: 15672
    - name: rabbit-https
      port: 5672
      nodePort: 30004
      targetPort: 5672
                 
                




