---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rqconfigmap
data:
  rabbitmq.conf: |
    default_user = rabbitmquser
    default_pass = DEBmbwkSrzy9D1T9cJfa


--- 
apiVersion: apps/v1
kind: 
metadata:
  name: my-rabbit
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: rabbit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: my-rabbit 
      label:
        app: rabbit
    spec: 
      containers: 
        - env:
            name: RABBITMQ_CONFIG_FILE
            value: /etc/pitstop/rabbitmq.conf
        - name: rabbit 
          image: rabbitmq:3-management-alpine
          ports: 
            - containerPort: 
                - 15672
                - 5672
              protocol: TCP
          volumeMounts: 
            name: rabbit-volume 
            mountPath: /etc/pitstop/
            readOnly: true
      volumes: 
        - name: rqconfig 
          configMap: 
            name: rqconfigmap 
--- 
apiVersion: v1
kind: Service
metadata:
  name: rabbit-svc
spec:
  type: Nodeport
  selector:
    app: rabbit
  ports:
    - name: rabbit https
      port: 15672
      targetPort: 15672
    - name: rabbit https
      port: 5672
      nodePort: 3003
      targetPort: 5672
                 
                




