--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: sql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: my-sql
      labels:
        app: sql
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io/instance-id
                  operator: In
                  values: 
                   - i-09eeca7831f6b52b2
      containers: 
        - name: sql
          env:
             - name: ACCEPT_EULA
               value: "Y"
             - name: MSSQL_PID
               value: Developer
             - name: SA_PASSWORD
               value: 8jkGh47hnDw89Haq8LN2
          image: mcr.microsoft.com/azure-sql-edge
          ports: 
            - containerPort: 1433
              protocol: TCP 
      restartPolicy: Always           
--- 
apiVersion: v1
kind: Service
metadata:
  name: sql-svc
spec:
  type: NodePort
  selector:
    app: sql
  ports:
    - name: sql-https
      nodePort: 30005
      port:  1433
      targetPort: 1433        