--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: sql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: my-sql
      labels:
        app: sql
    spec: 
      containers: 
        - name: sql
          env:
             - name: ACCEPT_EULA
               value: Y
             - name: MSSQL_PID
               value: Developer
             - name: SA_PASSWORD
               value: 8jkGh47hnDw89Haq8LN2
          image: mcr.microsoft.com/azure-sql-edge
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports: 
            - containerPort: 1433
              protocol: TCP 
      restartPolicy: Always           
--- 
apiVersion: v1
kind: Service
metadata:
  name: sql-svc
spec:
  type: NodePort
  selector:
    app: sql
  ports:
    - name: sql-https
      nodePort: 30005
      port:  1433
      targetPort: 1433        