--- 
apiVersion: apps/v1
kind: 
metadata:
  name: my-sql
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: sql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: my-sql
      label:
        app: sql
    spec: 
      containers: 
        - env:
           - name: ACCEPT_EULA
             value: Y
           - name: MSSQL_PID
             value: Developer
           - name: SA_PASSWORD
             value: 8jkGh47hnDw89Haq8LN2
        - name: sql
          image: mcr.microsoft.com/azure-sql-edge
          ports: 
            - containerPort: 1433
              protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: sql-svc
spec:
  type: Nodeport
  selector:
    app: sql
  ports:
    - name: sql https
      nodePort: 3004
      port:  1433
      targetPort: 1433        