--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: timeservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: timeservice-server
      labels:
        app: timeservice
    spec: 
      containers: 
         - name: timeservice
           env:
             - name: DOTNET_ENVIRONMENT
               value: Production
           image: pitstop/timeservice:1.0
      restartPolicy: Always    
                