--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: timeservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: timeservice-server
      labels:
        app: timeservice
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io/instance-id 
                  operator: In
                  values: 
                   - i-09eeca7831f6b52b2
      containers: 
         - name: timeservice
           env:
             - name: DOTNET_ENVIRONMENT
               value: Production
           image: pitstop/timeservice:1.0
      restartPolicy: Always    
                