--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: vehicle
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: vehicle-server
      labels:
        app: vehicle
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io 
                  operator: In
                  values: 
                   - instance-id=i-09eeca7831f6b52b2
      containers: 
        - name: vehicle 
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: pitstop/vehiclemanagementapi:1.0
          ports: 
           - containerPort: 5000
             protocol: TCP 
      restartPolicy: Always            
--- 
apiVersion: v1
kind: Service
metadata:
  name: vehicle-svc
spec:
  type: NodePort
  selector:
    app: vehicle
  ports:
    - name: mail-https
      port: 5000
      nodePort: 30006 
      targetPort: 5000
         