--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: webapp-server
      labels:
        app: webapp
    spec: 
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: alpha.eksctl.io 
                  operator: In 
                  values: 
                   - instance-id=i-09eeca7831f6b52b2
      containers:
         - name: vehicle 
           env:
             - name: ASPNETCORE_ENVIRONMENT
               value: Production
           image:  pitstop/webapp:1.0
           ports: 
            - containerPort: 7005
              protocol: TCP
      restartPolicy: Always             
--- 
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  type: LoadBalancer 
  selector:
    app: webapp
  ports:
    - name: mail-https
      port: 7005
      targetPort: 7005 

         