--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: webapp-server
      label:
        app: webapp
    spec: 
      containers:
         - name: vehicle 
           env:
             - name: ASPNETCORE_ENVIRONMENT
               value: Production
           image:  pitstop/webapp:1.0
           resources:
             requests:
               memory: "64Mi"
               cpu: "250m"
             limits:
               memory: "128Mi"
               cpu: "500m"
           ports: 
            - containerPort: 7005
              protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: mail https
      port: 7005
      nodePort: 30007
      targetPort: 7005
         