--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: workshop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: workshop-server
      labels:
        app: workshop
    spec: 
      containers:
         - name: workshop 
           env:
             - name: ASPNETCORE_ENVIRONMENT
               value: Production
           image: pitstop/workshopmanagementapi:1.0
           resources:
             requests:
               memory: "64Mi"
               cpu: "250m"
             limits:
               memory: "128Mi"
               cpu: "500m"
           ports: 
             - containerPort: 5200
               protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: workshop-svc
spec:
  type: NodePort
  selector:
    app: workshop
  ports:
    - name: workshop-https
      port: 5200
      nodePort: 30008
      targetPort: 5200
         