--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagementeventhandler-server
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabel:
      app: workshopmanagementeventhandler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template: 
    metadata:
      name: workshopmanagementeventhandler-server
      labels:
        app: workshopmanagementeventhandler
    spec: 
      containers: 
          - env:
              - name: DOTNET_ENVIRONMENT
                value: Production
            name: timeservice
            image: pitstop/workshopmanagementeventhandler:1.0
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m" 
      restartPolicy: Always               